services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: postgres:14.10
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - db:/data/postgres-cb
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  db:
